### PR TITLE
Strip leading byte-order marker from parsers

### PR DESCRIPTION
**Pull request by rodrigues**
Hello 👋

Some valid XML excel files might start with a special character (a leading BOM), this PR fixes parsing for this scenario.

Thanks!

### CODE REVIEW

**Comment by xavier** [comment]
Hello and thanks for your contribution.

I'm surprised you ran into this issue since we are already supposed to strip the BOM in the `Utils.ensure_utf8/1` which should be called for every XML file we extract.

I must admit that I never got to test this with a real `.xlsx` file since the person who reported the bug initially never provided one.

Would you be able to pinpoint why the current approach doesn't work?
Or provide a test file?

**Comment by rodrigues** [comment]
@xavier I have a file I can't share that reproduces the error.

```elixir
> XlsxReader.open(path)
{:error,
 %Saxy.ParseError{
   reason: {:token, :lt},
   binary: "\uFEFF<?xml version=\"1.0\" encoding=\"utf-8\"?><workbook xmlns:r=" <> ...,
   position: 0
 }}
```

we could also fix it by adding a clause at this point:

```elixir
  # ...
  def ensure_utf8("\uFEFF" <> utf8), do: {:ok, utf8}
  def ensure_utf8(utf8), do: {:ok, utf8}
```

I'm not sure about the other clauses, if they fix another corner case with utf-16.

**Comment by xavier** [comment]
Would you please try this branch: https://github.com/xavier/xlsx_reader/tree/fix-bom-issue with your test file?

I've changed the way we handle the BOM and added a test for UTF-8 with BOM.

**Comment by rodrigues** [comment]
thanks @xavier, with you branch it opens successfully 👌

**Comment by rodrigues** [comment]
@xavier can you release a new version please?

merci!

**Pull request closed without merging**
